# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    # Ignore log.Log() return values - standard Go logging pattern
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log
      - (*github.com/go-kit/log.Logger).Log
      - (github.com/go-kit/log/level.Logger).Log

issues:
  # Don't limit the number of issues
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - mixin
    - vendor

